default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  # socket: /var/run/mysqld/mysqld.sock
  host: mysql

development:
  <<: *default
  database: <%= ENV["MYSQL_DATABASE"] %>