version: "3.9"

services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: "2.7.2"
        BUNDLER_VERSION: "2.1.4"
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - ./test-app:/app:cached
      - gems:/usr/local/bundle/gems
      - rails_cache:/app/tmp/cache
    depends_on:
      - mysql
    command: bundle exec rails server -b 0.0.0.0

  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
    # env_file: ./test-app/.env
    restart: always

volumes:
  rails_cache:
  gems:
  mysql:

# /usr/local/lib/ruby/site_ruby/2.7.0/bundler.rb